// GENERATED by scripts/research/build-exam-stats.mjs — do not hand-edit.
// Sources: research/hunt2/robustness-0929.md, research/hunt2/holdout-exam-0929.json.

export type BatteryRow = { rank: number; id: string; family: string; mode: string; assets: number; excess: number | null; survives: boolean; worstCase: number | null; failed: string[] };
export type HoldoutRow = { id: string; verdict: string; excessAnnual: number; p: number; cagr: number; bhCagr: number; maxDD: number; bhMaxDD: number; controlExcessAnnual: number; beatsControl: boolean; firstDay: string; lastDay: string; days: number };

export const EXAM_TESTED = 20;
export const EXAM_SURVIVED = 14;
export const EXAM_BATTERY: BatteryRow[] = [
  {
    "rank": 2,
    "id": "s29-cx-fng-cond-mom",
    "family": "momentum",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.395,
    "survives": true,
    "worstCase": 0.27399999999999997,
    "failed": []
  },
  {
    "rank": 3,
    "id": "r25-crypto-btcbeta-low",
    "family": "equity-factors",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.389,
    "survives": true,
    "worstCase": 0.264,
    "failed": []
  },
  {
    "rank": 4,
    "id": "r27-crypto-lowbeta-rankw",
    "family": "equity-factors",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.318,
    "survives": true,
    "worstCase": 0.244,
    "failed": []
  },
  {
    "rank": 5,
    "id": "r27-crypto-mom-buffer",
    "family": "momentum",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.316,
    "survives": true,
    "worstCase": 0.228,
    "failed": []
  },
  {
    "rank": 7,
    "id": "r27-crypto-scaled-trend",
    "family": "trend",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.261,
    "survives": true,
    "worstCase": 0.17600000000000002,
    "failed": []
  },
  {
    "rank": 8,
    "id": "r27-cx-tsmom-vote3h",
    "family": "trend",
    "mode": "signal",
    "assets": 18,
    "excess": 0.258,
    "survives": true,
    "worstCase": 0.15,
    "failed": []
  },
  {
    "rank": 1,
    "id": "r27-cx-tsmom28-fngfear",
    "family": "sentiment",
    "mode": "signal",
    "assets": 18,
    "excess": 0.406,
    "survives": true,
    "worstCase": 0.13699999999999998,
    "failed": []
  },
  {
    "rank": 9,
    "id": "social-ta-vwma-cross",
    "family": "momentum",
    "mode": "signal",
    "assets": 18,
    "excess": 0.23199999999999998,
    "survives": true,
    "worstCase": 0.096,
    "failed": []
  },
  {
    "rank": 18,
    "id": "s29-etf-dynamic-hedge-selection",
    "family": "other",
    "mode": "portfolio",
    "assets": 8,
    "excess": 0.038,
    "survives": true,
    "worstCase": 0.034,
    "failed": []
  },
  {
    "rank": 6,
    "id": "mlq-feature-neutral-momentum",
    "family": "momentum",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.292,
    "survives": true,
    "worstCase": 0.03,
    "failed": []
  },
  {
    "rank": 14,
    "id": "r24b-lo-industry-momentum",
    "family": "equity-factors",
    "mode": "portfolio",
    "assets": 171,
    "excess": 0.055,
    "survives": true,
    "worstCase": 0.027999999999999997,
    "failed": []
  },
  {
    "rank": 11,
    "id": "macro-crypto-btc-dominance-altseason-rotation",
    "family": "macro-intermarket",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.132,
    "survives": true,
    "worstCase": 0.017,
    "failed": []
  },
  {
    "rank": 20,
    "id": "r24b-rev-low-turnover",
    "family": "mean-reversion-statarb",
    "mode": "portfolio",
    "assets": 171,
    "excess": 0.03,
    "survives": true,
    "worstCase": 0.01,
    "failed": []
  },
  {
    "rank": 15,
    "id": "r24b-lo-xsec-momentum-12-1",
    "family": "equity-factors",
    "mode": "portfolio",
    "assets": 171,
    "excess": 0.053,
    "survives": true,
    "worstCase": 0.009000000000000001,
    "failed": []
  },
  {
    "rank": 10,
    "id": "r27-crypto-boom-only",
    "family": "trend",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.182,
    "survives": false,
    "worstCase": null,
    "failed": [
      "-25% settings"
    ]
  },
  {
    "rank": 12,
    "id": "s29-us-vix-beta",
    "family": "volatility",
    "mode": "portfolio",
    "assets": 40,
    "excess": 0.062,
    "survives": false,
    "worstCase": null,
    "failed": [
      "exposure-matched hold"
    ]
  },
  {
    "rank": 13,
    "id": "r25-qqq-agg-volmanaged",
    "family": "volatility",
    "mode": "portfolio",
    "assets": 2,
    "excess": 0.057999999999999996,
    "survives": false,
    "worstCase": null,
    "failed": [
      "drop top asset"
    ]
  },
  {
    "rank": 16,
    "id": "macro-hy-credit-spread-risk-off",
    "family": "macro-intermarket",
    "mode": "portfolio",
    "assets": 25,
    "excess": 0.047,
    "survives": false,
    "worstCase": null,
    "failed": [
      "drop top asset",
      "exposure-matched hold"
    ]
  },
  {
    "rank": 17,
    "id": "r25-qqq-agg-dualmom",
    "family": "trend",
    "mode": "portfolio",
    "assets": 2,
    "excess": 0.038,
    "survives": false,
    "worstCase": null,
    "failed": [
      "drop top asset"
    ]
  },
  {
    "rank": 19,
    "id": "mlq-risk-parity-crypto",
    "family": "volatility",
    "mode": "portfolio",
    "assets": 18,
    "excess": 0.033,
    "survives": false,
    "worstCase": null,
    "failed": [
      "-25% settings"
    ]
  }
];
export const HOLDOUT_ALPHA = 0.025;
export const HOLDOUT_BOUNDARY = "2025-03-15";
export const HOLDOUT_CONFIRMED = 0;
export const HOLDOUT: HoldoutRow[] = [
  {
    "id": "r25-crypto-btcbeta-low",
    "verdict": "NOT CONFIRMED: not confirmed, underpowered",
    "excessAnnual": 0.11516190476910859,
    "p": 0.32083958020989506,
    "cagr": 0.358835310496175,
    "bhCagr": 0.24367340572706642,
    "maxDD": 0.4675785077073331,
    "bhMaxDD": 0.5270773066500016,
    "controlExcessAnnual": -0.3409710447231026,
    "beatsControl": true,
    "firstDay": "2025-03-15",
    "lastDay": "2026-09-27",
    "days": 562
  },
  {
    "id": "r27-crypto-scaled-trend",
    "verdict": "NOT CONFIRMED",
    "excessAnnual": -0.06865157616730211,
    "p": 1,
    "cagr": 0.1750218295597643,
    "bhCagr": 0.24367340572706642,
    "maxDD": 0.2631788309082991,
    "bhMaxDD": 0.5270773066500016,
    "controlExcessAnnual": -0.28900808315635285,
    "beatsControl": true,
    "firstDay": "2025-03-15",
    "lastDay": "2026-09-27",
    "days": 562
  }
];
