// GENERATED by scripts/research/build-registry.mjs — do not hand-edit these numbers.
// Source of truth: research/hunt2/ledger.jsonl -> research/STRATEGY-REGISTRY.json
// (latest row per id, __robN reruns folded into their base id, deep-validation
// CONTROL rows excluded entirely). public/research-registry.json is the trimmed
// copy the landing page fetches. Re-run `npm run research:registry` after any new test.

export const STRATEGIES_TESTED = 517; // distinct strategies, controls excluded
export const STRATEGY_UNIT = "strategies";
export const STRATEGY_FAMILIES = 31;
/** Individual scored runs behind those strategies (robustness reruns included). */
export const STRATEGY_TEST_RUNS = 595;
/** Strategies with a better point-estimate return than buy-and-hold after costs. */
export const STRATEGIES_AHEAD = 87;
/** Strategies ahead of buy-and-hold with p < 0.05 before any multiple-testing correction. */
export const STRATEGIES_SIGNIFICANT = 8;
/** Median strategy's CAGR minus buy-and-hold CAGR (fraction per year, negative = behind). */
export const MEDIAN_EXCESS_ANNUAL = -0.0987;
export const STRATEGIES_BY_ASSET_CLASS: Record<string, number> = {"crypto":146,"etf":138,"us_stock":233};

/** Benjamini-Hochberg family: every distinct non-control run that traded (research/hunt2/ledger.mjs). */
export const FDR_TESTS = 598;
export const FDR_Q_MAX = 0.1;
/** Runs that cleared the full gate (q, random controls, both halves, trades, net > 0, 2+ assets). */
export const FDR_PASSED = 0;
export const FDR_LOWEST_P = 0.0002;
export const FDR_LOWEST_Q = 0.1196;

/** Last bar any test could see; everything after it is held back. */
export const DISCOVERY_END_DATE = "2025-03-15";
export const LEDGER_FIRST_RUN = "2026-09-15";
export const LEDGER_LAST_UPDATED = "2026-09-29";

/** Sign persistence of excess/yr between the two halves of the discovery window (from the registry's halfExcess). */
export const HALF_PERSISTENCE = {"aheadFirstHalf":71,"aheadBothHalves":49,"aheadSecondHalfOnly":94,"aheadFullWindowAndBothHalves":49};

export type CostFamilyRow = { family: string; strategies: number; losesAtZeroCost: number; needsCheaper: number; aheadAtRealCost: number; medianExcessAtZeroCost: number };
/** Cost-to-breakeven (scripts/research/cost-sweep.mjs): each strategy re-run at 0/5/10/20bp per side; null until that sweep has run. */
export const COST_SWEEP: null | { strategies: number; losesAtZeroCost: number; needsCheaper: number; aheadAtRealCost: number; medianCostRatioNeedsCheaper: number; medianExcessAtZeroCost: number; byFamily: CostFamilyRow[] } = {
  "strategies": 211,
  "losesAtZeroCost": 196,
  "needsCheaper": 1,
  "aheadAtRealCost": 14,
  "medianCostRatioNeedsCheaper": 5.72,
  "medianExcessAtZeroCost": -0.1394,
  "byFamily": [
    {
      "family": "calendar",
      "strategies": 8,
      "losesAtZeroCost": 8,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.1966
    },
    {
      "family": "carry",
      "strategies": 1,
      "losesAtZeroCost": 1,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.8308
    },
    {
      "family": "equity-factors",
      "strategies": 17,
      "losesAtZeroCost": 17,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.1823
    },
    {
      "family": "event-driven",
      "strategies": 2,
      "losesAtZeroCost": 2,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.2035
    },
    {
      "family": "low-vol regime + breakout",
      "strategies": 1,
      "losesAtZeroCost": 1,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.627
    },
    {
      "family": "macro-intermarket",
      "strategies": 10,
      "losesAtZeroCost": 5,
      "needsCheaper": 0,
      "aheadAtRealCost": 5,
      "medianExcessAtZeroCost": -0.0122
    },
    {
      "family": "mean-reversion-statarb",
      "strategies": 10,
      "losesAtZeroCost": 10,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.1196
    },
    {
      "family": "mean_reversion",
      "strategies": 24,
      "losesAtZeroCost": 24,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.1834
    },
    {
      "family": "ml-quant-modern",
      "strategies": 11,
      "losesAtZeroCost": 10,
      "needsCheaper": 0,
      "aheadAtRealCost": 1,
      "medianExcessAtZeroCost": -0.0677
    },
    {
      "family": "momentum",
      "strategies": 18,
      "losesAtZeroCost": 14,
      "needsCheaper": 0,
      "aheadAtRealCost": 4,
      "medianExcessAtZeroCost": -0.1415
    },
    {
      "family": "open interest divergence",
      "strategies": 1,
      "losesAtZeroCost": 1,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.7877
    },
    {
      "family": "other",
      "strategies": 7,
      "losesAtZeroCost": 7,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.082
    },
    {
      "family": "seasonality",
      "strategies": 14,
      "losesAtZeroCost": 14,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.131
    },
    {
      "family": "sentiment",
      "strategies": 5,
      "losesAtZeroCost": 5,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.3944
    },
    {
      "family": "sentiment-altdata",
      "strategies": 1,
      "losesAtZeroCost": 1,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.1115
    },
    {
      "family": "social-ta",
      "strategies": 10,
      "losesAtZeroCost": 10,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.193
    },
    {
      "family": "trader-books",
      "strategies": 8,
      "losesAtZeroCost": 8,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.147
    },
    {
      "family": "trend",
      "strategies": 25,
      "losesAtZeroCost": 23,
      "needsCheaper": 0,
      "aheadAtRealCost": 2,
      "medianExcessAtZeroCost": -0.1007
    },
    {
      "family": "trend-managed-futures",
      "strategies": 10,
      "losesAtZeroCost": 10,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.0381
    },
    {
      "family": "vol regime + sentiment",
      "strategies": 1,
      "losesAtZeroCost": 1,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -0.5182
    },
    {
      "family": "volatility",
      "strategies": 26,
      "losesAtZeroCost": 23,
      "needsCheaper": 1,
      "aheadAtRealCost": 2,
      "medianExcessAtZeroCost": -0.1167
    },
    {
      "family": "volatility expansion signal",
      "strategies": 1,
      "losesAtZeroCost": 1,
      "needsCheaper": 0,
      "aheadAtRealCost": 0,
      "medianExcessAtZeroCost": -1.2083
    }
  ]
};

export type RandomClassRow = { assetClass: string; random: { n: number; p10: number; p50: number; p90: number; p95: number; beats95PctOfControls: number; under5PctOfControls: number }; tested: { n: number; p10: number; p50: number; p90: number; aboveRandomP95: number; aboveRandomMedian: number } };
/** Coin-flip strategies through the same harness (scripts/research/random-control-sweep.mjs), beside the tested ones; null until that sweep has run. */
export const RANDOM_CONTROL: null | { n: number; rejected: number; note: string; pBelow05: number; aheadOfBuyHold: number; beats95PctOfControls: number; under5PctOfControls: number; byAssetClass: RandomClassRow[] } = {
  "n": 300,
  "rejected": 0,
  "note": "100 seeded random long/flat signal strategies per daily universe, flip probabilities 0.02/0.05/0.1/0.2 cycled, default harness universe, real costs, discovery data only. Same evaluate() as the ledger; never written to it.",
  "pBelow05": 0,
  "aheadOfBuyHold": 1,
  "beats95PctOfControls": 41,
  "under5PctOfControls": 63,
  "byAssetClass": [
    {
      "assetClass": "crypto",
      "random": {
        "n": 100,
        "p10": -0.4605,
        "p50": -0.3062,
        "p90": -0.1586,
        "p95": -0.1025,
        "beats95PctOfControls": 8,
        "under5PctOfControls": 9
      },
      "tested": {
        "n": 146,
        "p10": -0.981,
        "p50": -0.4831,
        "p90": 0.1718,
        "aboveRandomP95": 34,
        "aboveRandomMedian": 58
      }
    },
    {
      "assetClass": "etf",
      "random": {
        "n": 100,
        "p10": -0.0661,
        "p50": -0.0479,
        "p90": -0.0316,
        "p95": -0.0284,
        "beats95PctOfControls": 7,
        "under5PctOfControls": 16
      },
      "tested": {
        "n": 138,
        "p10": -0.113,
        "p50": -0.0374,
        "p90": 0.0068,
        "aboveRandomP95": 54,
        "aboveRandomMedian": 79
      }
    },
    {
      "assetClass": "us_stock",
      "random": {
        "n": 100,
        "p10": -0.1473,
        "p50": -0.1058,
        "p90": -0.0595,
        "p95": -0.0496,
        "beats95PctOfControls": 26,
        "under5PctOfControls": 38
      },
      "tested": {
        "n": 233,
        "p10": -0.195,
        "p50": -0.1086,
        "p90": 0.0154,
        "aboveRandomP95": 84,
        "aboveRandomMedian": 112
      }
    }
  ]
};

export type FamilyLedgerRow = { family: string; strategies: number; ahead: number; significant: number; bestExcessAnnual: number; assetClasses: string[] };
export const FAMILY_LEDGER: FamilyLedgerRow[] = [
  {
    "family": "momentum",
    "strategies": 78,
    "ahead": 31,
    "significant": 2,
    "bestExcessAnnual": 0.3946,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "trend",
    "strategies": 71,
    "ahead": 15,
    "significant": 2,
    "bestExcessAnnual": 0.2609,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "volatility",
    "strategies": 55,
    "ahead": 6,
    "significant": 1,
    "bestExcessAnnual": 0.2023,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "mean_reversion",
    "strategies": 54,
    "ahead": 2,
    "significant": 0,
    "bestExcessAnnual": 0.0227,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "equity-factors",
    "strategies": 36,
    "ahead": 9,
    "significant": 2,
    "bestExcessAnnual": 0.3892,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "mean-reversion-statarb",
    "strategies": 28,
    "ahead": 2,
    "significant": 0,
    "bestExcessAnnual": 0.0301,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "other",
    "strategies": 28,
    "ahead": 1,
    "significant": 1,
    "bestExcessAnnual": 0.0376,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "seasonality",
    "strategies": 23,
    "ahead": 2,
    "significant": 0,
    "bestExcessAnnual": 0.0138,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "macro-intermarket",
    "strategies": 19,
    "ahead": 6,
    "significant": 0,
    "bestExcessAnnual": 0.1316,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "social-ta",
    "strategies": 19,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.0769,
    "assetClasses": [
      "crypto",
      "us_stock"
    ]
  },
  {
    "family": "sentiment",
    "strategies": 18,
    "ahead": 2,
    "significant": 0,
    "bestExcessAnnual": 0.4059,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "ml-quant-modern",
    "strategies": 12,
    "ahead": 1,
    "significant": 0,
    "bestExcessAnnual": 0.0098,
    "assetClasses": [
      "crypto",
      "us_stock"
    ]
  },
  {
    "family": "calendar",
    "strategies": 10,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.0202,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "event-driven",
    "strategies": 10,
    "ahead": 4,
    "significant": 0,
    "bestExcessAnnual": 0.0286,
    "assetClasses": [
      "us_stock"
    ]
  },
  {
    "family": "trend-managed-futures",
    "strategies": 10,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.0151,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "trader-books",
    "strategies": 8,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.1422,
    "assetClasses": [
      "us_stock"
    ]
  },
  {
    "family": "carry",
    "strategies": 7,
    "ahead": 1,
    "significant": 0,
    "bestExcessAnnual": 0.0162,
    "assetClasses": [
      "crypto",
      "etf"
    ]
  },
  {
    "family": "macro",
    "strategies": 6,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.0001,
    "assetClasses": [
      "crypto",
      "etf",
      "us_stock"
    ]
  },
  {
    "family": "oi-spot-disagreement",
    "strategies": 4,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.0036,
    "assetClasses": [
      "crypto"
    ]
  },
  {
    "family": "oil-shock-attribution",
    "strategies": 3,
    "ahead": 1,
    "significant": 0,
    "bestExcessAnnual": 0.0017,
    "assetClasses": [
      "etf"
    ]
  },
  {
    "family": "rate-decomposition",
    "strategies": 3,
    "ahead": 2,
    "significant": 0,
    "bestExcessAnnual": 0.0026,
    "assetClasses": [
      "etf"
    ]
  },
  {
    "family": "breadth",
    "strategies": 2,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.0363,
    "assetClasses": [
      "us_stock"
    ]
  },
  {
    "family": "breadth-dispersion",
    "strategies": 2,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.1086,
    "assetClasses": [
      "us_stock"
    ]
  },
  {
    "family": "credit-vol-disagreement",
    "strategies": 2,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.002,
    "assetClasses": [
      "etf"
    ]
  },
  {
    "family": "macro-disagreement",
    "strategies": 2,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.0059,
    "assetClasses": [
      "etf"
    ]
  },
  {
    "family": "volatility-disagreement",
    "strategies": 2,
    "ahead": 2,
    "significant": 0,
    "bestExcessAnnual": 0.0046,
    "assetClasses": [
      "etf"
    ]
  },
  {
    "family": "low-vol regime + breakout",
    "strategies": 1,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.6274,
    "assetClasses": [
      "crypto"
    ]
  },
  {
    "family": "open interest divergence",
    "strategies": 1,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.8158,
    "assetClasses": [
      "crypto"
    ]
  },
  {
    "family": "sentiment-altdata",
    "strategies": 1,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.1121,
    "assetClasses": [
      "etf"
    ]
  },
  {
    "family": "vol regime + sentiment",
    "strategies": 1,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -0.522,
    "assetClasses": [
      "crypto"
    ]
  },
  {
    "family": "volatility expansion signal",
    "strategies": 1,
    "ahead": 0,
    "significant": 0,
    "bestExcessAnnual": -1.809,
    "assetClasses": [
      "crypto"
    ]
  }
];

export const RESEARCH_HEADLINE =
  "517 strategies across 31 families. None beat buy-and-hold after costs by more than luck would explain.";

export const RESEARCH_SUBLINE =
  "517 distinct strategies across 31 families, 595 scored runs, all backtested with real costs against buy-and-hold. 87 finished ahead of buy-and-hold on the point estimate; 8 were significant at p < 0.05 before correction, and none survived correction for testing this many strategies at once.";
